# Generated by Django 5.0.7 on 2024-08-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='confirmpassword',
            field=models.CharField(default='some_default_value', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='emailid',
            field=models.EmailField(default='some_default_value', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='password',
            field=models.CharField(default='some_default_value', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='some_default_value', max_length=200),
        ),
    ]
