# Generated by Django 5.0.7 on 2024-08-06 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_item_confirmpassword_item_emailid_item_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='username',
        ),
    ]
