# Generated by Django 5.0.7 on 2024-08-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_name_item_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_percent', models.IntegerField(blank=True, null=True)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('num_sales', models.IntegerField(blank=True, null=True)),
                ('sizes_available', models.CharField(blank=True, max_length=255, null=True)),
                ('colors_available', models.CharField(blank=True, max_length=255, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=20, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('num_in_stock', models.IntegerField(blank=True, null=True)),
                ('related_sports', models.CharField(blank=True, max_length=255, null=True)),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
    ]
