# Generated by Django 5.0.7 on 2024-08-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='lat',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='product',
            name='long',
            field=models.FloatField(default='0'),
        ),
    ]
