# Generated by Django 5.0.7 on 2024-08-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_product_city_product_country_product_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='city',
        ),
        migrations.RemoveField(
            model_name='product',
            name='country',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='long',
        ),
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='country',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='lat',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='item',
            name='long',
            field=models.FloatField(default='0'),
        ),
    ]
