# Generated by Django 5.0.7 on 2024-09-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_userprofile_cart_userprofile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, default='null', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='landmark',
            field=models.CharField(blank=True, default='null', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='number',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.CharField(blank=True, default='null', max_length=250, null=True),
        ),
    ]
