# Generated by Django 5.0.7 on 2024-09-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_userprofile_address_userprofile_landmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='item_ordered',
            field=models.JSONField(default=list),
        ),
    ]
